[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "fmba"
version = "0.1.0"
description = "Finite Memory Belief Approximation"
authors = [
    { name = "Mintae Kim" }
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "numpy",
    "scipy",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "black",
    "isort",
    "ruff",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["fmba*"]

[tool.black]
line-length = 100
target-version = ["py310"]

[tool.isort]
profile = "black"